name: shattably
description: A Flutter home-services marketplace for customers and skilled workers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <3.6.0'
  flutter: '>=3.24.4 <3.25.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  dio: 5.7.0
  intl: 0.19.0
  conditional_builder_null_safety: 0.0.6
  shared_preferences: 2.3.2
  smooth_page_indicator: 1.2.0+3
  share_plus: 7.2.2
  firebase_core: 2.32.0
  firebase_auth: 4.20.0
  firebase_storage: 11.7.7
  cloud_firestore: 4.17.5
  firebase_messaging: 14.9.4
  image_picker: 1.1.2
  camera: 0.10.6
  drop_down_list: 0.0.5
  flutter_local_notifications: 17.2.3
  awesome_dialog: 3.2.1
  url_launcher: 6.3.1
  path: 1.9.0
  syncfusion_flutter_datepicker: 26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
